# Dockerfile
FROM alpine:3.20

# Install PG client and AWS CLI
RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk add --no-cache \
    postgresql17-client \
    aws-cli 


CMD ["sh"]
